// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQsqK4gFpN0n-oSxNaOmP0L4MBWm1QQ90',
    appId: '1:57565123141:web:c79490abe9980ce35e492c',
    messagingSenderId: '57565123141',
    projectId: 'chat-app-youssif-2026',
    authDomain: 'chat-app-youssif-2026.firebaseapp.com',
    storageBucket: 'chat-app-youssif-2026.firebasestorage.app',
    measurementId: 'G-ZHTL98LXP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdQMq4lhyGHy3XsC80GiJ204zsNe0v5bQ',
    appId: '1:57565123141:android:9ca7c12a9ecdb3fb5e492c',
    messagingSenderId: '57565123141',
    projectId: 'chat-app-youssif-2026',
    storageBucket: 'chat-app-youssif-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJsJUWT6xXeAKRCKPUq4FYysF97XkjTU',
    appId: '1:57565123141:ios:3dd1842b0f4940745e492c',
    messagingSenderId: '57565123141',
    projectId: 'chat-app-youssif-2026',
    storageBucket: 'chat-app-youssif-2026.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdJsJUWT6xXeAKRCKPUq4FYysF97XkjTU',
    appId: '1:57565123141:ios:3dd1842b0f4940745e492c',
    messagingSenderId: '57565123141',
    projectId: 'chat-app-youssif-2026',
    storageBucket: 'chat-app-youssif-2026.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQsqK4gFpN0n-oSxNaOmP0L4MBWm1QQ90',
    appId: '1:57565123141:web:64f205819519fcaa5e492c',
    messagingSenderId: '57565123141',
    projectId: 'chat-app-youssif-2026',
    authDomain: 'chat-app-youssif-2026.firebaseapp.com',
    storageBucket: 'chat-app-youssif-2026.firebasestorage.app',
    measurementId: 'G-R6BEJZXX9D',
  );
}
